# Imagen base ligera
FROM node:20-alpine

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

RUN apk add --no-cache git bash

# Copiamos los archivos de dependencias primero
COPY package*.json ./

# Instalamos dependencias como root
RUN npm ci

# Copiamos el resto del proyecto
COPY . .

# ✅ Ajustamos permisos antes de cambiar de usuario
RUN chown -R node:node /app

# Ahora cambiamos de usuario
USER node

# Exponemos puerto
EXPOSE 3000

# Comando por defecto
CMD ["npm", "run", "dev"]
